# Generated by Django 6.0.6 on 2026-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('pendente', 'Pendente'), ('lido', 'Lido'), ('respondido', 'Respondido'), ('fechado', 'Fechado')], default='novo', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
