# Generated by Django 6.0.6 on 2026-07-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('pending', 'Pendente'), ('read', 'Lido'), ('replied', 'Respondido'), ('closed', 'Fechado')], default='new', max_length=20),
        ),
    ]
